#!/usr/bin/env python3
"""Rewrite weak example sentences in data/words.json with kid-friendly context."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORDS_PATH = ROOT / "data" / "words.json"

# Every grade 1 / 4 / 6 word gets a clear, natural sentence that uses the word.
SENTENCES: dict[str, str] = {
    # Grade 1
    "all": "All of the kids lined up for recess.",
    "an": "I ate an apple after lunch.",
    "and": "Tom and Sue played tag.",
    "as": "She ran as fast as she could.",
    "bat": "He swung the bat and hit the ball.",
    "be": "Please be kind to your friends.",
    "been": "I have been to the zoo twice.",
    "bell": "The school bell rang at noon.",
    "big": "That truck is too big for the garage.",
    "block": "She stacked one block on top of another.",
    "bone": "The dog chewed on a bone.",
    "brick": "Dad laid a red brick on the path.",
    "bug": "A tiny bug crawled on the leaf.",
    "bun": "I bought a warm cinnamon bun.",
    "by": "Please sit by the window.",
    "cap": "He put on his baseball cap.",
    "chop": "Help me chop the carrots for dinner.",
    "cob": "We ate buttered corn on the cob.",
    "come": "Come inside before it rains.",
    "cow": "The cow chewed grass in the field.",
    "cut": "Please cut the paper with scissors.",
    "dig": "We dig holes in the sandbox.",
    "dog": "My dog wagged its tail.",
    "down": "Climb down the ladder carefully.",
    "drop": "Don't drop the glass of milk.",
    "dry": "Hang the towels until they are dry.",
    "duck": "A duck swam across the pond.",
    "each": "Each child got one sticker.",
    "fed": "She fed the cat before school.",
    "flow": "Watch the water flow down the stream.",
    "for": "This gift is for my brother.",
    "fox": "A fox ran across the snowy field.",
    "from": "I walked home from school.",
    "game": "We played a board game after dinner.",
    "glad": "I am glad you came to my party.",
    "go": "Let's go to the park.",
    "has": "She has a blue backpack.",
    "have": "Do you have a pencil I can borrow?",
    "his": "His lunchbox is on the shelf.",
    "hit": "She hit the ball with the bat.",
    "hook": "Hang your coat on the hook.",
    "hop": "The frog can hop across the rocks.",
    "hut": "We built a small hut from sticks.",
    "ink": "The pen left a spot of ink on my paper.",
    "is": "This is my favorite book.",
    "kick": "Kick the ball toward the goal.",
    "let": "Please let me help you.",
    "load": "Help me load the boxes into the car.",
    "long": "The hallway is very long.",
    "lot": "There are a lot of stars tonight.",
    "low": "The plane flew low over the field.",
    "luck": "I wish you good luck on the test.",
    "man": "The man waved from the porch.",
    "mat": "Wipe your feet on the mat.",
    "mob": "A noisy mob filled the street.",
    "mop": "Use the mop to clean the floor.",
    "more": "May I have more juice, please?",
    "mug": "She drank cocoa from a big mug.",
    "must": "You must wear a helmet on your bike.",
    "name": "Please write your name on the line.",
    "no": "There are no cookies left.",
    "not": "Please do not run in the hall.",
    "note": "I left a note on the fridge.",
    "on": "The book is on the table.",
    "or": "Would you like milk or water?",
    "other": "The other shoe is under the bed.",
    "part": "Which part of the puzzle goes here?",
    "pay": "I will pay for the tickets.",
    "people": "Many people waited for the bus.",
    "pig": "The pig rolled in the mud.",
    "pit": "Don't fall into that deep pit.",
    "play": "Let's play outside after homework.",
    "pool": "We swam in the pool all afternoon.",
    "ran": "He ran to catch the school bus.",
    "roof": "Snow covered the roof of the house.",
    "rose": "A pink rose bloomed in the garden.",
    "run": "I can run to the fence and back.",
    "rut": "The wagon wheel stuck in a muddy rut.",
    "sell": "They sell fresh apples at the market.",
    "shake": "Shake the juice box before you drink.",
    "she": "She read the story out loud.",
    "sick": "I stayed home because I felt sick.",
    "snack": "An apple makes a healthy snack.",
    "sob": "The sad puppy began to sob.",
    "sock": "I can't find my other sock.",
    "spin": "Watch the toy top spin on the floor.",
    "spoon": "Stir the soup with a spoon.",
    "stay": "Please stay in your seat.",
    "sun": "The sun warmed the playground.",
    "tame": "The tame rabbit sat on my lap.",
    "tan": "His shoes were a light tan color.",
    "tell": "Please tell me your favorite animal.",
    "their": "Their coats are by the door.",
    "there": "Put your shoes over there.",
    "time": "What time does the movie start?",
    "tooth": "I lost a tooth last night.",
    "tuck": "Tuck the blanket under the mattress.",
    "up": "Look up at the bright moon.",
    "use": "You may use my markers.",
    "water": "Please water the plants today.",
    "way": "Which way leads to the library?",
    "well": "She can sing very well.",
    "when": "When does recess begin?",
    "wig": "The actor wore a curly wig.",
    "win": "Our team hopes to win the game.",
    "wood": "We built the shelf out of wood.",
    "words": "Choose kind words when you speak.",
    "would": "Would you like a sandwich?",
    "write": "Please write your name neatly.",
    "your": "Is this your lunchbox?",
    # Grade 4
    "abuse": "Never abuse a tool by using it the wrong way.",
    "across": "We walked across the wooden bridge.",
    "actor": "The actor bowed after the play.",
    "against": "Lean the ladder against the wall.",
    "alarm": "The fire alarm woke everyone up.",
    "ankle": "She twisted her ankle during soccer.",
    "axe": "The ranger used an axe to chop wood.",
    "bargain": "The used bike was a real bargain.",
    "basin": "Wash your hands in the basin.",
    "bay": "Boats floated quietly in the bay.",
    "believe": "I believe you told the truth.",
    "bridge": "Cars crossed the long bridge.",
    "bubble": "A shiny bubble floated into the air.",
    "cannon": "The old fort still had a rusty cannon.",
    "castle": "The castle stood on a rocky hill.",
    "catch": "Try to catch the ball with both hands.",
    "center": "Stand in the center of the circle.",
    "certain": "I am certain this answer is correct.",
    "chain": "The bike chain needed oil.",
    "character": "My favorite character in the book is brave.",
    "children": "The children lined up for lunch.",
    "choir": "The choir sang at the school concert.",
    "college": "My cousin will start college next year.",
    "community": "Our community planted trees in the park.",
    "compass": "Use a compass to find north.",
    "compatible": "These two games are compatible with our tablet.",
    "compose": "We will compose a short song in music class.",
    "congress": "Congress meets to make new laws.",
    "contest": "She entered an art contest at school.",
    "corner": "Meet me at the corner of the street.",
    "cotton": "My soft shirt is made of cotton.",
    "couldn't": "I couldn't open the jammed door.",
    "council": "The student council planned the dance.",
    "courage": "It takes courage to try something new.",
    "cousin": "My cousin is visiting this weekend.",
    "damage": "The storm caused damage to the roof.",
    "deposit": "Dad made a deposit at the bank.",
    "destroyed": "The old shed was destroyed by the storm.",
    "difference": "Can you spot the difference in these pictures?",
    "distraction": "The loud TV was a distraction while I studied.",
    "early": "We arrived early for the show.",
    "except": "Everyone went outside except Mia.",
    "export": "The farm will export apples to other states.",
    "extend": "Please extend your arm for the nurse.",
    "fatal": "The game warned that one wrong move could be fatal.",
    "filled": "She filled the pitcher with water.",
    "fingers": "Count on your fingers if it helps.",
    "fountain": "We tossed a coin into the fountain.",
    "fresh": "The bakery smells like fresh bread.",
    "friends": "I invited my friends to the picnic.",
    "fugitive": "In the story, the fugitive hid in the forest.",
    "garbage": "Take the garbage out to the curb.",
    "goose": "A goose honked beside the pond.",
    "hammer": "He used a hammer to hang the picture.",
    "heaven": "The sunset looked like a painting of heaven.",
    "hollow": "The birds nested inside the hollow log.",
    "hostile": "The desert can be a hostile place for travelers.",
    "hotel": "Our family stayed in a hotel near the beach.",
    "husband": "In the story, the husband packed lunch for the trip.",
    "illegal": "It is illegal to drive without a license.",
    "itself": "The door closed by itself.",
    "jewel": "The crown held a sparkling jewel.",
    "keyboard": "Type your password on the keyboard.",
    "kingdom": "The map showed a faraway kingdom.",
    "language": "Spanish is a language I want to learn.",
    "lower": "Please lower your voice in the library.",
    "member": "She is a member of the chess club.",
    "memory": "That trip is my happiest memory.",
    "mountain": "Snow covered the top of the mountain.",
    "muffin": "I packed a blueberry muffin for snack.",
    "neutral": "The referee stayed neutral during the game.",
    "nutrients": "Vegetables give your body important nutrients.",
    "object": "Name every object on the science table.",
    "perhaps": "Perhaps we can finish the puzzle tonight.",
    "pineapple": "We cut a sweet pineapple for dessert.",
    "poison": "The label warned that the liquid was poison.",
    "population": "The city's population grew last year.",
    "portal": "In the game, a glowing portal opened.",
    "potato": "Mash the potato with a little butter.",
    "prime": "Two is the smallest prime number.",
    "prince": "The prince rode through the village.",
    "problem": "We solved the math problem together.",
    "products": "The store sells many healthy products.",
    "professional": "A professional chef taught our cooking class.",
    "public": "The park is a public place for everyone.",
    "puzzle": "This jigsaw puzzle has one hundred pieces.",
    "queen": "The queen waved from the balcony.",
    "rather": "I would rather walk than wait for the bus.",
    "region": "Our region had heavy rain this week.",
    "reject": "Please don't reject a kind offer of help.",
    "remember": "Remember to pack your library book.",
    "reptile": "A snake is a reptile with dry scales.",
    "resist": "Try to resist eating dessert before dinner.",
    "retain": "Plants retain water in their roots.",
    "return": "Please return the book to the shelf.",
    "salute": "The soldiers gave a sharp salute.",
    "seventy": "Grandpa turned seventy years old today.",
    "since": "We have lived here since last summer.",
    "site": "The building site was full of trucks.",
    "slavery": "We studied how slavery harmed people in history class.",
    "speed": "Check your speed on the bike path.",
    "subject": "Science is my favorite subject.",
    "suddenly": "Suddenly the lights went out.",
    "syllables": "Clap the syllables in the word butterfly.",
    "thirty": "There are thirty students in our class.",
    "today": "Today we have art after lunch.",
    "tomatoes": "We picked ripe tomatoes from the garden.",
    "transport": "Trucks transport food to the store.",
    "tutor": "A tutor helped me with reading.",
    "usefulness": "We discussed the usefulness of a checklist.",
    "vocal": "She is very vocal about fairness on the team.",
    "yourself": "Give yourself time to finish the test.",
    # Grade 6
    "accidentally": "I accidentally spilled juice on my homework.",
    "ambulance": "An ambulance raced to the accident.",
    "appearance": "His neat appearance impressed the judges.",
    "appointment": "I have a dentist appointment on Friday.",
    "autumn": "Leaves turn bright colors in autumn.",
    "capable": "She is capable of solving hard puzzles.",
    "comfortable": "This chair is soft and comfortable.",
    "complain": "Don't complain until you try the new lunch.",
    "concentration": "Quiet rooms help my concentration.",
    "cooperation": "Winning took cooperation from the whole team.",
    "creative": "His creative poster won first prize.",
    "decision": "Choosing a book was a hard decision.",
    "denominator": "In three-fourths, four is the denominator.",
    "depth": "Measure the depth of the pool carefully.",
    "descendant": "She is a descendant of early settlers.",
    "disagreement": "They settled their disagreement calmly.",
    "disastrous": "The disastrous storm flooded the road.",
    "discussion": "Our class had a discussion about recycling.",
    "distance": "Measure the distance between the two desks.",
    "earliest": "The earliest bus leaves at six o'clock.",
    "edition": "I bought the newest edition of the atlas.",
    "elevator": "Take the elevator to the third floor.",
    "emergency": "Call an adult in an emergency.",
    "emptiness": "The emptiness of the quiet gym felt strange.",
    "encouragement": "Her encouragement helped me keep trying.",
    "encyclopedia": "I looked up volcanoes in the encyclopedia.",
    "establish": "The club will establish new rules today.",
    "excitement": "Excitement filled the room before the show.",
    "experience": "Camping was a new experience for me.",
    "exterior": "Paint the exterior of the shed this weekend.",
    "faucet": "Turn off the faucet when you finish.",
    "fierce": "A fierce wind shook the trees.",
    "forgiveness": "He asked for forgiveness after the mistake.",
    "further": "Walk a little further down the path.",
    "gallon": "We bought a gallon of milk.",
    "grateful": "I am grateful for your help.",
    "grief": "The story showed the family's grief with care.",
    "hangar": "The airplane waited inside the hangar.",
    "hanger": "Hang your shirt on a hanger.",
    "headache": "Loud noise gave me a headache.",
    "heroes": "Firefighters are everyday heroes.",
    "honorable": "Returning the wallet was an honorable choice.",
    "horizon": "The sun sank below the horizon.",
    "hunger": "Hunger made us hurry to lunch.",
    "ignore": "Please don't ignore the safety rules.",
    "importance": "He explained the importance of honesty.",
    "independence": "The holiday celebrates independence.",
    "injury": "An ice pack helped her ankle injury.",
    "inquire": "Inquire at the desk if you need help.",
    "instead": "I chose water instead of soda.",
    "intermission": "We bought popcorn during intermission.",
    "invitation": "I mailed an invitation to the party.",
    "involve": "The project will involve measuring and drawing.",
    "legal": "Wearing a seat belt is a legal requirement.",
    "liquid": "Water is a liquid that can freeze.",
    "loaves": "She baked two loaves of bread.",
    "location": "Mark the treasure's location on the map.",
    "manner": "Speak in a polite manner.",
    "meant": "I meant to call you yesterday.",
    "medicine": "Take your medicine with a glass of water.",
    "minus": "Ten minus four equals six.",
    "misunderstand": "Don't misunderstand the directions on the test.",
    "mixture": "Stir the pancake mixture until it is smooth.",
    "mouth": "Cover your mouth when you cough.",
    "multiple": "The word has multiple meanings.",
    "musician": "The musician practiced the flute daily.",
    "mute": "Press mute if the video is too loud.",
    "nationality": "She wrote her nationality on the form.",
    "negative": "Zero is not a negative number.",
    "noticeable": "There was a noticeable crack in the vase.",
    "numerator": "In one-half, one is the numerator.",
    "occur": "Thunderstorms can occur in the afternoon.",
    "official": "The official score was posted online.",
    "original": "Keep your original receipt in a safe place.",
    "partial": "We only finished a partial section of the mural.",
    "passenger": "Each passenger needs a ticket.",
    "performance": "Her piano performance earned loud applause.",
    "personal": "Keep your personal password private.",
    "persuade": "Can you persuade him to join the club?",
    "piano": "She practiced the piano every evening.",
    "predict": "Scientists predict rain for tomorrow.",
    "prefer": "I prefer apples to oranges.",
    "principal": "The principal spoke at the assembly.",
    "purchase": "We will purchase supplies for the project.",
    "purse": "She put her keys in her purse.",
    "quote": "Copy the quote carefully from the book.",
    "radius": "Draw a circle with a two-inch radius.",
    "rapid": "The river's rapid current looked dangerous.",
    "ratio": "The ratio of boys to girls was even.",
    "recently": "I recently finished a mystery novel.",
    "referred": "The doctor referred her to a specialist.",
    "rehearse": "The actors will rehearse the play tonight.",
    "relief": "Finishing the test brought me relief.",
    "remarkable": "The museum had a remarkable dinosaur fossil.",
    "remind": "Please remind me to pack my lunch.",
    "remote": "They camped in a remote forest.",
    "replacement": "I need a replacement for my broken pencil.",
    "roam": "Deer roam freely through the valley.",
    "routine": "Brushing your teeth is part of a healthy routine.",
    "safety": "Wear a helmet for safety on your bike.",
    "sailor": "The sailor tied the rope to the dock.",
    "scarcely": "We had scarcely sat down when the show began.",
    "scientific": "We followed the scientific method in lab.",
    "sentence": "Write a complete sentence with a capital letter.",
    "session": "Our practice session lasted one hour.",
    "shampoo": "Wash your hair with shampoo and rinse well.",
    "shelves": "Put the books back on the shelves.",
    "shorten": "Shorten the rope so it won't drag.",
    "silent": "The library was silent during reading time.",
    "simply": "The directions were simply written and clear.",
    "skillful": "The skillful potter shaped the clay cup.",
}

WEAK = re.compile(
    r"(^We practiced |^I can spell |^Can you write | in a sentence\.|"
    r"list includes|three times\.|^The test included | for homework\.|"
    r"^Spell .+ carefully\.|reviewed .+ in class|is on our list|"
    r"^The story mentioned |^In science, we studied |^Hand me the |"
    r"^We need to .+ before lunch\.|^She spelled )",
    re.I,
)


def main() -> None:
    words = json.loads(WORDS_PATH.read_text())
    updated = 0
    missing = []
    for entry in words:
        if entry["grade_level"] not in (1, 4, 6):
            continue
        key = entry["word"].lower()
        if key not in SENTENCES:
            missing.append(entry["word"])
            continue
        new = SENTENCES[key]
        if entry.get("example_sentence") != new:
            entry["example_sentence"] = new
            updated += 1
        if key not in new.lower():
            raise SystemExit(f"Sentence missing word: {key} -> {new}")
        if WEAK.search(new):
            raise SystemExit(f"Weak sentence slipped through: {key} -> {new}")

    if missing:
        raise SystemExit(f"Missing sentences for: {', '.join(missing)}")

    WORDS_PATH.write_text(json.dumps(words, indent=2) + "\n")
    print(f"updated {updated} example sentences")


if __name__ == "__main__":
    main()
